models/task.py
from utils.db import db


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String(80), nullable=False)
    isFinished = db.Column(db.Boolean, nullable=False)

    def __init__(self, description, isFinished=False) -> None:
        self.description = description
        self.isFinished = isFinished

    def __repr__(self) -> str:
        return f"Task({self.id}, '{self.description}', {self.isFinished})"

forms/registerForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class RegisterForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("register")

    def validate_username(self, username):
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            raise ValidationError("the username already exists")

forms/taskCreateForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import InputRequired, Length


class TaskCreateForm(FlaskForm):
    description = StringField(
        validators=[
            InputRequired(),
            Length(min=3, max=80),
        ],
        render_kw={"placeholder": "description..."},
    )

    isFinished = BooleanField()

    submit = SubmitField("create")

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from routes.todolist import todolist
from utils.db import db

app = Flask(__name__)

app.config.from_object("config.BaseConfig")

SQLAlchemy(app)

app.register_blueprint(todolist)

routes/todolist.py
from flask import Blueprint, render_template, url_for, redirect
from forms.taskCreateForm import TaskCreateForm
from models.task import Task
from utils.db import db

todolist = Blueprint("todolist", __name__)


@todolist.route("/")
def home():
    return render_template("home.html")


@todolist.route("/main")
def main():
    taskList = Task.query.all()
    return render_template("todolist/home.html", tasks=taskList)


@todolist.route("/create", methods=["GET", "POST"])
def create():
    form = TaskCreateForm()
    if form.validate_on_submit():
        description = form.description.data
        newTask = Task(description)
        db.session.add(newTask)
        db.session.commit()
        return redirect(url_for("todolist.main"))
    return render_template("todolist/create.html", form=form)


@todolist.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    currentTask = Task.query.get(id)
    form = TaskCreateForm(
        description=currentTask.description,
        isFinished=currentTask.isFinished,
    )
    if form.validate_on_submit():
        currentTask.description = form.description.data
        currentTask.isFinished = form.isFinished.data
        db.session.add(currentTask)
        db.session.commit()
        return redirect(url_for("todolist.main"))
    return render_template("todolist/update.html", form=form, id=id)


@todolist.route("/delete/<int:id>")
def delete(id):
    currentTask = Task.query.get(id)
    db.session.delete(currentTask)
    db.session.commit()
    return redirect(url_for("todolist.main"))

templates/home.html
{% extends 'layout.html' %}
{% block title %}web app home{% endblock %}
{% block contents %}
<h1>web app home</h1>
<br>
<a href="{{ url_for('todolist.main') }}">go to todolist</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block contents %}{% endblock %}
</body>

</html>

templates/todolist/create.html
{% extends 'layout.html' %}
{% block title %}create task{% endblock %}
{% block contents %}
<h1>create task</h1>
<br>
create task
<br>
<form action="{{ url_for('todolist.create') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.description.label }}
    {{ form.description }}<br>
    {{ form.isFinished.label }}
    {{ form.isFinished }}<br>
    {{ form.submit }}
</form>
{% endblock %}

templates/todolist/home.html
{% extends 'layout.html' %}
{% block title %}todolist home{% endblock %}
{% block contents %}
<h1>todolist home</h1>
<br>
<a href="{{ url_for('todolist.create') }}">create new task</a>
<br>
<table border="1">
    <thead>
        <tr>
            <th>id</th>
            <th>description</th>
            <th>is finished</th>
            <th>actions</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.id }}</td>
            <td>{{ task.description }}</td>
            <td>{{ task.isFinished }}</td>
            <th><a href="{{ url_for('todolist.update', id=task.id) }}">update</a></th>
            <th><a href="#">finish</a></th>
            <th><a href="{{ url_for('todolist.delete', id=task.id) }}">delete</a></th>
        </tr>
        {% endfor%}
    </tbody>
</table>
{% endblock %}

templates/todolist/update.html
{% extends 'layout.html' %}
{% block title %}update task{% endblock %}
{% block contents %}
<h1>update task</h1>
<br>
update task
<br>
<form action="{{ url_for('todolist.update', id=id) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.description.label }}
    {{ form.description }}<br>
    {{ form.isFinished.label }}
    {{ form.isFinished }}<br>
    {{ form.submit }}
</form>
{% endblock %}